### ISSUE TITLE
Listener arguments behavior breaks

### ISSUE THREAD

**Issue by Akryum** [nickmessing/babel-plugin-jsx-event-modifiers#4]
Using the plugin breaks the Vue argument behavior for event listeners, that is you should be able to pass as many argument as you want (even when not using event modifiers).

For example:

```jsx
function handleSort(field, sorting) {
  console.log(field, sorting)
}

return <Column onSort={handleSort}/>
```

For `Column`:

```jsx
render (h, { props, listeners }) {
  function handleSortClick () {
    // ...
    listeners.sort(props.field, newSorting)
  }
  // ...
}
```

Currently, only the first argument is passed (all listeners are wrapped in a single-argument function).

```js
sort($event) {
  handleSort($event);
}
```

It should at last be:

```js
sort(...args) {
  handleSort(...args);
}
```

**Comment by nickmessing** [comment]
@Akryum, thank you for spending time with this project, this indeed is a bug and will be fixed asap.

**Comment by Akryum** [comment]
Thanks! :)
