### ISSUE TITLE
App still doesn't run after installing package.

### ISSUE THREAD

**Issue by AshwinTayson** [nickmessing/babel-plugin-jsx-event-modifiers#6]
Hello I'm new to rendering in VueJS. I have a piece of code that renders a custom component. I couldn't attach event handlers as it threw error v-on:click is xml and JSX allows only onClick. After searching in JSX forum I found a link to this page. Here is the code I'm using

```
return (
        <div id='hideColumnsMarker' class='relative'>
          <v-btn icon small class='grey lighten-4' id='hideColumnsButton'  @click='this.hideColumns(true)'>
            <v-icon>{ this.hideColumnsFlag ? 'chevron_left' : 'chevron_right' }</v-icon>
          </v-btn>
          <span>{column.label}</span>
        </div>
      )
```

I still get the error 'Unexpected token @'. I have added 'transform-runtime' in babelrc. Am I missing something?

**Comment by nickmessing** [comment]
you need to use `onClick`, check out [example](https://github.com/nickmessing/babel-plugin-jsx-event-modifiers#example) how to use it with modifiers if wanted.
